name: Build and create production release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'site/**'
    - 'src/**'
    - 'gatsby-browser.js'
    - 'gatsby-config.js'
    - 'gatsby-node.js'
    - 'gatsby-ssr.js'
    - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      VERSION: '0.0'

    steps:

    # Ensure this action is not on master/main branches
    - name: Check branch is in master/main
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
      run: exit 1

    # Install NodeJS
    - name: Use Node.js ${{ github.event.inputs.logLevel }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ github.event.inputs.logLevel }}

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    #
    # Create and tag release 
    #
    - name: Create release tag
      id: release_tag
      run: |
        set -x
        git fetch --all
        git remote -v
        git tag -l

        git config user.email "$(git log -1 --pretty=format:'%an')"
        git config user.name "$(git log -1 --pretty=format:'%ae')"
        git log

        set +e
        last_tag=$(git for-each-ref \
          --sort=-creatordate \
          --format '%(refname)' refs/tags \
          | grep "refs/tags/${VERSION}" \
          | head -1)
        set -e

        build_number=$(basename "$last_tag" | cut -d '.' -f3)
        [[ -n $build_number ]] || build_number=-1
        release_tag=${VERSION}.$((build_number+1))

        last_commit_msg=$(git log -1 --pretty=%B)
        git tag -a ${release_tag} -m "$last_commit_msg"
        git push --follow-tags

        echo "::set-output name=value::$(echo ${release_tag})"

    - name: Echo release tag
      run: 'echo "Release tag: ${{steps.release_tag.outputs.value}}"'

    #
    # Configure and run site content build
    #

    # - name: Create AWS Amplify configuration file
    #   run: echo -e "${{ secrets.AWS_AMPLIFY_EXPORTS }}" > src/aws-exports.ts

    # - name: Build site content
    #   run: |
    #     npm install
    #     npm install gatsby-cli
    #     node_modules/.bin/gatsby build
