name: Build and Publish Dev Site

on:
  workflow_dispatch:
    input:
      nodeVersion:
        description: 'Node version'
        required: true
        default: '12.x'
  push:
    branches: [ dev ]
    paths:
    - 'site/**'
    - 'src/**'
    - 'gatsby-browser.js'
    - 'gatsby-config.js'
    - 'gatsby-node.js'
    - 'gatsby-ssr.js'
    - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
        
    # Ensure this action is not on master/main branches
    - name: Check branch is not master/main
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: exit 1

    # Install NodeJS
    - name: Use Node.js ${{ github.event.inputs.logLevel }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ github.event.inputs.logLevel }}

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    #
    # Configure and run site content build
    #

    - name: Create AWS Amplify configuration file
      run: echo -e "${{ secrets.AWS_AMPLIFY_EXPORTS }}" > src/aws-exports.ts

    - name: Build site content
      run: |
        npm install
        npm install gatsby-cli
        node_modules/.bin/gatsby build

    - name: Upload site content
      uses: actions/upload-artifact@master
      with:
        name: site-content
        path: ${{ github.workspace }}/public
        
  publish:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    # Setup default environment for running Terraform
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_domain: appbricks.io
      TF_VAR_publish_path: ${{ github.workspace }}/public

    steps:
    
    # Ensure this action is not on master/main branches
    - name: Check branch is not master/main
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: exit 1

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Install the latest version of AWS CLI
    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    
    # Retrieve built content from previous job
    - name: Download site content
      uses: actions/download-artifact@master
      with:
        name: site-content
        path: ${{ github.workspace }}/public

    # Initialize a new or existing Terraform working 
    # directory by creating initial files, loading any 
    # remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        TF_VAR_env=${GITHUB_REF##*/} terraform init \
          -backend-config="key=website/appbricks-io_${TF_VAR_env}" \
          -backend-config="bucket=appbricks-tfstate-useast1" \
          build/publish

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        TF_VAR_env=${GITHUB_REF##*/} terraform plan \
          build/publish

    # Apply Terraform plan and deploy site to a dev url
    - name: Terraform Plan
      run: |
        TF_VAR_env=${GITHUB_REF##*/} terraform apply -auto-approve \
          build/publish
  